import json, os
from pathlib import Path
from playwright.sync_api import sync_playwright
origin=os.environ.get('PPG_ORIGIN','http://100.96.13.84:8082')
out=Path(os.environ.get('PPG_EVIDENCE','/home/byron/.hermes/cache/scratch'));out.mkdir(parents=True,exist_ok=True)
checks=[]
def check(ok,name):
 if not ok: raise AssertionError(name)
 checks.append(name);print('PASS:',name)
with sync_playwright() as p:
 b=p.chromium.launch(executable_path='/home/byron/.cache/ms-playwright/chromium-1223/chrome-linux64/chrome',headless=True,args=['--no-sandbox'])
 ctx=b.new_context(viewport={'width':1600,'height':1000})
 if origin.startswith('http://100.'):
  def forward(route):
   try: route.fulfill(response=route.fetch(url=route.request.url.replace(origin,'http://172.19.0.2'),headers={**route.request.headers,'host':'100.96.13.84:8082'},max_redirects=0,timeout=60000))
   except Exception: route.abort()
  ctx.route(origin+'/**',forward)
 page=ctx.new_page();errors=[];page.on('pageerror',lambda e: errors.append(str(e)))
 page.goto(origin+'/product/the-portable-folding-kings-table/?ppg_qa=1',wait_until='domcontentloaded',timeout=90000)
 page.wait_for_selector('.ppg-initialized',timeout=30000)
 root=page.locator('[data-ppg]');root.scroll_into_view_if_needed();page.wait_for_timeout(500)
 check(root.count()==1,'one gallery only on real Brizy page')
 check(page.locator('[data-ppg-original]').count()==1,'original intro row retained but hidden')
 check(page.locator('.ppg-preserved img').count()==2,'both existing folding/rolling icons retained')
 check(page.locator('.ppg-thumb').count()==6,'six existing product images including featured')
 metrics=page.locator('.ppg-thumbnails').evaluate('(e)=>({client:e.clientWidth,scroll:e.scrollWidth})')
 check(metrics['scroll']>metrics['client'],'more than four thumbnails overflow horizontally')
 check(root.locator('.ppg-main-image').evaluate('(e)=>e.complete&&e.naturalWidth>0'),'real main image loaded')
 initial=root.locator('.ppg-main-image').get_attribute('src')
 root.locator('.ppg-thumb').nth(1).click();page.wait_for_function('(src)=>document.querySelector(".ppg-main-image").getAttribute("src")!==src',arg=initial)
 check(root.locator('.ppg-thumb').nth(1).get_attribute('aria-pressed')=='true','click swaps real main image and active thumbnail')
 root.locator('.ppg-thumb').nth(1).focus();page.keyboard.press('End');page.wait_for_timeout(1000)
 check(root.locator('.ppg-thumb').last.get_attribute('aria-pressed')=='true','keyboard End selects final image')
 root.locator('.ppg-quote .pqb-open').click()
 page.wait_for_function('!document.querySelector("#pqb-dialog").classList.contains("pqb-hidden")')
 page.wait_for_selector('#pqb-fields label',timeout=30000)
 check(page.locator('#pqb-fields').inner_text().strip()!='','existing product-specific quote modal loads fields')
 page.keyboard.press('Escape');page.wait_for_timeout(250)
 check(page.locator('#pqb-dialog').evaluate('(e)=>e.classList.contains("pqb-hidden")'),'quote modal closes with Escape')
 root.screenshot(path=str(out/'ppg-real-desktop.png'))
 page.set_viewport_size({'width':390,'height':844});page.wait_for_timeout(400);root.scroll_into_view_if_needed()
 metrics=page.evaluate('''()=>({page:document.documentElement.scrollWidth,width:innerWidth,title:document.querySelector('.ppg-title').getBoundingClientRect().top,image:document.querySelector('.ppg-stage').getBoundingClientRect().top,thumbs:document.querySelector('.ppg-thumbnails').getBoundingClientRect().top,description:document.querySelector('.ppg-description').getBoundingClientRect().top,root:document.querySelector('.ppg').getBoundingClientRect().width})''')
 check(metrics['page']<=metrics['width']+1,'mobile page has no horizontal overflow')
 check(metrics['title']<metrics['image']<metrics['thumbs']<metrics['description'],'mobile title/image/thumbs/description order')
 root.screenshot(path=str(out/'ppg-real-mobile.png'))
 root.locator('.ppg-quote .pqb-open').click();page.wait_for_selector('#pqb-fields label');check(page.locator('#pqb-dialog').is_visible(),'mobile quote modal opens')
 page.keyboard.press('Escape')
 check(not errors,'no real-page JavaScript exceptions')
 Path(out/'ppg-real-results.json').write_text(json.dumps({'origin':origin,'checks':checks,'errors':errors},indent=2))
 b.close()
print('PASS:',len(checks),'real-page browser checks')
